import { citizenSafetyApi, type EmergencyRecord, type EvacuationRoute, type SafetyContext } from './api/citizen-safety.api';

type Message = { id: string; role: 'assistant' | 'user'; text: string; createdAt: number };
type SpeechRecognitionCtor = new () => any;

const CHAT_HISTORY_KEY = 'jalrakshak:citizen-ai-history:v1';
const WELCOME_TEXT = 'Hi, I’m NavCat. I can help with flood safety, live risk, weather, routes, safe destinations, and responder updates.';

let latestRoute: EvacuationRoute | null = null;
let latestSafety: SafetyContext | null = null;
let latestEmergency: EmergencyRecord | null = null;
let messages: Message[] = loadHistory();
let voiceEnabled = false;
let listening = false;
let crisisMode = false;
let lastLocationKey = '';
let refreshTimer: number | null = null;

function createMessage(role: Message['role'], text: string): Message { return { id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`, role, text, createdAt:Date.now() }; }
function loadHistory(): Message[] { try { const p=JSON.parse(localStorage.getItem(CHAT_HISTORY_KEY)??'[]'); return Array.isArray(p)?p.filter((x:any)=>(x.role==='assistant'||x.role==='user')&&typeof x.text==='string').slice(-80):[]; } catch{return [];} }
function saveHistory(){try{localStorage.setItem(CHAT_HISTORY_KEY,JSON.stringify(messages.slice(-80)));}catch{}}
function citizenName(){return document.querySelector<HTMLElement>('.sidebar-user strong')?.textContent?.trim()||'there';}
function locationLabel(){const r=document.querySelector<HTMLElement>('.location-line')?.textContent?.replace(/\s+/g,' ').trim()??'';return r.replace(/^⌖\s*/,'').replace(/\s*·\s*LIVE\s*$/,'').trim()||'your current area';}
function getCurrentPosition():Promise<GeolocationPosition|null>{if(!navigator.geolocation)return Promise.resolve(null);return new Promise(r=>navigator.geolocation.getCurrentPosition(r,()=>r(null),{enableHighAccuracy:true,timeout:4500,maximumAge:15000}));}
async function refreshContext(){const p=await getCurrentPosition();if(p){const k=`${p.coords.latitude.toFixed(3)},${p.coords.longitude.toFixed(3)}`;if(k!==lastLocationKey||!latestSafety){lastLocationKey=k;try{latestSafety=await citizenSafetyApi.getContext(p.coords.latitude,p.coords.longitude);}catch{}}}try{const e=await citizenSafetyApi.listEmergencies();latestEmergency=e.filter(x=>!x.is_demo&&x.status!=='cancelled').sort((a,b)=>Date.parse(b.updated_at??b.created_at)-Date.parse(a.updated_at??a.created_at))[0]??null;}catch{}}
function speak(t:string){if(!voiceEnabled||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=crisisMode?.9:1;window.speechSynthesis.speak(u);}
function formatDistance(m:number){return m>=1000?`${(m/1000).toFixed(1)} kilometers`:`${Math.round(m)} meters`;}
function escapeHtml(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));}
function isGibberish(raw:string){const compact=raw.toLowerCase().replace(/[^a-z]/g,'');if(compact.length<7)return false;const vowels=(compact.match(/[aeiou]/g)||[]).length;const known=/(flood|safe|route|weather|rain|river|help|responder|sos|evac|map|location|where|risk|medical|scared|stuck|hello|thank|guide|find|take|current|shelter|road)/.test(compact);return !known&&(vowels/compact.length<.22||/(.)\1\1/.test(compact));}
function isOutOfScope(t:string){return /(write.*code|programming|homework|essay|stock|crypto|movie|game|recipe|celebrity|politics|math problem|translate|dating|sports score|joke)/i.test(t);}
function safeReply(input:string):string{
 const raw=input.trim(),text=raw.toLowerCase(),name=citizenName(),place=locationLabel(),risk=latestSafety,route=latestRoute,emergency=latestEmergency;
 if(isGibberish(raw)) return `I didn’t understand that, ${name}. Try asking me about your location, flood risk, weather, a safe destination, your route, or responder help.`;
 if(isOutOfScope(text)) return `Sorry, ${name} — that’s outside my scope. I’m NavCat, so I stay focused on flood safety, evacuation, live weather and risk context, routes, safe locations, and emergency response.`;
 if(/^(hi|hello|hey|hiya|good morning|good afternoon|good evening)[!.,?\s]*$/i.test(raw))return `Hello ${name}. How can I help you today?`;
 if(/^(how are you|how's it going|how is it going)[!.,?\s]*$/i.test(raw))return `I’m ready to help, ${name}. What do you need right now?`;
 if(/(what can you do|what do you do|who are you)/i.test(text))return `I’m NavCat, JalRakshak’s safety assistant. Ask me naturally about your current location, flood risk, weather, evacuation routes, route changes, safe destinations, SOS, or responder status.`;
 if(/^(thanks|thank you|thx|ty)[!.,?\s]*$/i.test(raw))return `You’re welcome, ${name}. I’m here if you need another safety check or direction.`;
 const afterExplicit=/(i'm safe now|i am safe now|we are safe|we're safe|it's over|it is over|after the flood|response is complete|rescued)/i.test(text);
 if(afterExplicit){crisisMode=false;return `I’m glad you reached a safer point, ${name}. Stay somewhere safe and check whether anyone with you needs help. I can check weather or route conditions, or stay with you for a while.`;}
 if(/(scared|panic|afraid|terrified|shaking|overwhelmed|flood water|went through|in the water|stuck|trapped)/i.test(text))crisisMode=true;
 if(/(can't evacuate|cannot evacuate|stuck|trapped|need rescue)/i.test(text))return `If moving would put you in more danger, stay where you are. I can take you directly to Emergency Help so your GPS and safety context can be shared with responders.`;
 if(/(medical|hurt|injured|sick)/i.test(text))return `I can take you directly to Emergency Help to request medical assistance and share your location.`;
 if(/(scared|panic|afraid|terrified|shaking|overwhelmed)/i.test(text))return `I’m here with you, ${name}. We can do this one step at a time. ${route?`Your current destination is ${route.destination_name}.`:'I can find a safe destination from your current location.'}`;
 if(/(where am i|my location|current location|locate me)/i.test(text))return `You’re currently near ${place}. I can use that location to calculate a safe route on the Live Map.`;
 if(/(find|take|guide|route|directions|navigate).*(safe|safety|shelter|evacuat|destination|location|place)|where should i (go|evacuate)/i.test(text)){
   if(route)return `I found your current plan: ${route.destination_name}, about ${formatDistance(route.distance_m)} away and ${Math.max(1,Math.round(route.duration_s/60))} minutes. Open Live Map to see the route and start guidance.`;
   return `I can do that from your current location near ${place}. Open Live Map, tap “Use my location,” and JalRakshak will calculate the safest available destination and road route. You can ask me about any step without starting from the beginning.`;
 }
 if(/(am i safe|my risk|risk right now|safe right now)/i.test(text)){if(!risk)return `I don’t have a fresh risk reading yet. I can use your location to get one.`;return `Your current JalRakshak model is ${risk.prototype_risk_level.toUpperCase()} at ${risk.prototype_risk_score}/100 near ${place}. Rain expected in the next 6 hours is ${risk.precipitation_next_6h_mm.toFixed(1)} mm. This is modeled context, not an official warning.`;}
 if(/(rain|raining|weather|dangerous rain)/i.test(text)){if(!risk)return `I don’t have the latest weather context yet.`;return `The current feed shows ${risk.precipitation_next_6h_mm.toFixed(1)} mm of rain over the next 6 hours${risk.precipitation_probability_max_6h!=null?` with up to ${risk.precipitation_probability_max_6h}% probability`:''}.`;}
 if(/(why.*route|explain.*route|why.*chosen)/i.test(text)){if(!route)return `There isn’t an active route yet. You can ask me to find one from your current location.`;return `JalRakshak compared ${route.alternatives_considered} road options. ${route.screening_status==='complete'?`${route.rejected_count??0} were rejected and ${route.viable_count??0} remained viable. `:''}The recommended route goes to ${route.destination_name}.`;}
 if(/(route changed|reroute|still safe|route update|changed midway|change my plan)/i.test(text)){if(!route)return `No current route is loaded yet.`;return `The latest plan is ${route.destination_name}, about ${formatDistance(route.distance_m)} away. If the route analysis changes while you’re moving, NavCat will surface the new plan instead of keeping you on the older route.`;}
 if(/(responder|sos|help.*way|response status)/i.test(text)){if(!emergency)return `I don’t see an active SOS right now. I can take you to Emergency Help if you need a responder.`;return `Your latest SOS is ${emergency.status.replace('_',' ')}.${emergency.responder_name?` ${emergency.responder_name} is assigned.`:''}`;}
 return `I can help with flood safety, ${name}, but I’m not sure what you mean. Ask me about your current location, risk, weather, a safe destination, route guidance, or responder help.`;
}
function renderMessages(){const v=messages.length?messages:[createMessage('assistant',WELCOME_TEXT)];return v.map(m=>`<div class="ai-message ${m.role}" data-message-id="${escapeHtml(m.id)}"><div class="ai-message-wrap"><div class="ai-bubble">${escapeHtml(m.text)}</div>${messages.length?`<button type="button" class="ai-delete-message" data-ai-delete="${escapeHtml(m.id)}" aria-label="Delete this message">×</button>`:''}</div></div>`).join('');}
function quickActions(){return [['risk','My risk'],['route','Safest route'],['explain','Explain route'],['weather','Weather update'],['responder','Responder status'],['scared',"I'm scared"],['stuck',"I'm stuck"],['medical','Medical help'],['guide','Guide me']].map(([k,l])=>`<button type="button" data-ai-quick="${k}">${l}</button>`).join('');}
function renderAssistant(section:HTMLElement){const focused=document.activeElement?.matches?.('[data-ai-input]')??false;const draft=(document.querySelector<HTMLInputElement>('[data-ai-input]')?.value??'');section.className=`citizen-ai-screen ${crisisMode?'crisis-mode':''}`;section.innerHTML=`<div class="ai-header"><div class="ai-mode-controls"><span class="ai-chat-pill">💬 Chat</span><button type="button" class="ai-voice-toggle ${voiceEnabled?'active':''}" data-ai-voice>${voiceEnabled?'🔊 Voice on':'🔈 Voice off'}</button></div><div class="ai-history-controls"></div><span class="ai-brand-label">NavCat</span></div><div class="ai-layout"><section class="ai-chat-card"><div class="ai-messages" aria-live="polite">${renderMessages()}</div><div class="ai-quick-actions">${quickActions()}</div><form class="ai-input-row"><button type="button" class="ai-mic ${listening?'listening':''}" data-ai-mic>${listening?'■':'🎙'}</button><input type="text" data-ai-input placeholder="Ask NavCat…" autocomplete="off" value="${escapeHtml(draft)}"/><button type="submit" class="ai-send">Send</button></form><div class="ai-disclaimer">NavCat uses JalRakshak safety context. GPS, routing, hazard screening, and SOS remain deterministic app systems.</div></section></div>`;wireAssistant(section);setTimeout(()=>{const b=section.querySelector<HTMLElement>('.ai-messages');if(b)b.scrollTop=b.scrollHeight;const i=section.querySelector<HTMLInputElement>('[data-ai-input]');if(focused&&i){i.focus({preventScroll:true});try{i.setSelectionRange(i.value.length,i.value.length);}catch{}}},0);}
async function addUserMessage(section:HTMLElement,text:string){const c=text.trim();if(!c)return;messages.push(createMessage('user',c));saveHistory();renderAssistant(section);await refreshContext();const reply=safeReply(c);messages.push(createMessage('assistant',reply));saveHistory();renderAssistant(section);speak(reply);}
function deleteMessage(section:HTMLElement,id:string){messages=messages.filter(m=>m.id!==id);saveHistory();renderAssistant(section);}
function clearChat(section:HTMLElement){messages=[];crisisMode=false;saveHistory();if('speechSynthesis'in window)window.speechSynthesis.cancel();renderAssistant(section);}
function startVoice(section:HTMLElement){const w=window as any,R=(w.SpeechRecognition||w.webkitSpeechRecognition)as SpeechRecognitionCtor|undefined;if(!R){messages.push(createMessage('assistant','Voice input is not supported in this browser.'));saveHistory();renderAssistant(section);return;}const r=new R();r.lang='en-US';r.interimResults=false;r.continuous=false;listening=true;renderAssistant(section);r.onresult=(e:any)=>{listening=false;void addUserMessage(section,e.results?.[0]?.[0]?.transcript??'');};r.onerror=()=>{listening=false;renderAssistant(section);};r.onend=()=>{if(listening){listening=false;renderAssistant(section);}};r.start();}
function wireAssistant(section:HTMLElement){section.querySelector<HTMLFormElement>('.ai-input-row')?.addEventListener('submit',e=>{e.preventDefault();const i=section.querySelector<HTMLInputElement>('[data-ai-input]');if(i)void addUserMessage(section,i.value);});section.querySelector<HTMLButtonElement>('[data-ai-mic]')?.addEventListener('click',()=>startVoice(section));section.querySelector<HTMLButtonElement>('[data-ai-voice]')?.addEventListener('click',()=>{voiceEnabled=!voiceEnabled;if(!voiceEnabled&&'speechSynthesis'in window)window.speechSynthesis.cancel();renderAssistant(section);});section.querySelector<HTMLButtonElement>('[data-ai-clear]')?.addEventListener('click',()=>clearChat(section));section.querySelectorAll<HTMLButtonElement>('[data-ai-delete]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.aiDelete)deleteMessage(section,b.dataset.aiDelete);}));section.querySelectorAll<HTMLButtonElement>('[data-ai-quick]').forEach(b=>b.addEventListener('click',()=>{const p:Record<string,string>={risk:'Am I safe right now?',route:'Find me the safest route from my current location.',explain:'Why did you choose this route?',weather:'Is the rain dangerous right now?',responder:'What is my responder status?',scared:"I'm scared.",stuck:"I'm stuck and can't evacuate.",medical:'I need medical help.',guide:'Guide me to safety.'};void addUserMessage(section,p[b.dataset.aiQuick??'']??'');}));}
function maybeEnhanceAssistant(){const p=document.querySelector<HTMLElement>('.figma-placeholder-panel');if(p?.querySelector('h2')?.textContent?.trim()==='AI Assistant'){void refreshContext().finally(()=>renderAssistant(p));if(refreshTimer==null)refreshTimer=window.setInterval(()=>void refreshContext(),12000);return;}if(!document.querySelector('.citizen-ai-screen')&&refreshTimer!=null){clearInterval(refreshTimer);refreshTimer=null;}}

window.addEventListener('jalrakshak:route-analysis',(event)=>{
 const next=(event as CustomEvent<EvacuationRoute>).detail;
 if(next) latestRoute=next;
});

const observer=new MutationObserver(()=>maybeEnhanceAssistant());
observer.observe(document.body,{childList:true,subtree:true