import { citizenSafetyApi } from './api/citizen-safety.api';
import './responder-live-map-enhancer.css';

type LatLng={latitude:number;longitude:number};
type RouteCandidate={distanceM:number;durationS:number;geometry:[number,number][];safetyScore:number;status:'recommended'|'viable'|'rejected';reason:string;rejectionReasons?:string[]};
type Handoff={incidentId:string;responderPosition:LatLng;candidates:RouteCandidate[];updatedAt:string};
const HANDOFF_KEY='jalrakshak:responder-route-handoff';
let showRoutes=true;let showRisk=true;let scheduled=false;

function fmtDistance(m:number){return m>=1609.344?`${(m/1609.344).toFixed(1)} mi`:`${Math.max(1,Math.round(m*3.28084))} ft`;}
function fmtDuration(s:number){const min=Math.max(1,Math.round(s/60));return min>=60?`${Math.floor(min/60)}h ${min%60}m`:`${min} min`;}
function readHandoff():Handoff|null{try{const raw=sessionStorage.getItem(HANDOFF_KEY);if(!raw)return null;const parsed=JSON.parse(raw) as Handoff;return parsed?.incidentId&&parsed?.responderPosition&&Array.isArray(parsed?.candidates)?parsed:null;}catch{return null;}}
function parseBounds(src:string){try{const url=new URL(src,window.location.href);const raw=url.searchParams.get('bbox');if(!raw)return null;const [minLng,minLat,maxLng,maxLat]=raw.split(',').map(Number);if([minLng,minLat,maxLng,maxLat].some(v=>!Number.isFinite(v)))return null;return{minLng,minLat,maxLng,maxLat};}catch{return null;}}
function project(lon:number,lat:number,b:{minLng:number;minLat:number;maxLng:number;maxLat:number}){const x=((lon-b.minLng)/(b.maxLng-b.minLng))*100,y=(1-(lat-b.minLat)/(b.maxLat-b.minLat))*100;return{x:Math.max(-8,Math.min(108,x)),y:Math.max(-8,Math.min(108,y))};}
function routeSvg(handoff:Handoff,bounds:{minLng:number;minLat:number;maxLng:number;maxLat:number}){return `<svg class="live-route-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Responder route analysis">${handoff.candidates.map((route)=>{if(route.geometry.length<2)return'';const points=route.geometry.map(([lon,lat])=>{const p=project(lon,lat,bounds);return`${p.x},${p.y}`;}).join(' ');return`<polyline class="${route.status}" points="${points}"/>`;}).join('')}</svg>`;}
async function startGuidance(handoff:Handoff){const recommended=handoff.candidates.find(r=>r.status==='recommended');if(!recommended)return;try{const incident=await citizenSafetyApi.getEmergency(handoff.incidentId);if(incident.status==='assigned')await citizenSafetyApi.updateEmergency(incident.id,{status:'en_route',responder_id:incident.responder_id??undefined,responder_name:incident.responder_name??undefined});const url=`https://www.google.com/maps/dir/?api=1&origin=${handoff.responderPosition.latitude},${handoff.responderPosition.longitude}&destination=${incident.latitude},${incident.longitude}&travelmode=driving`;window.open(url,'_blank','noopener,noreferrer');const note=document.querySelector<HTMLElement>('[data-live-route-note]');if(note)note.textContent='Guidance started · responder status is EN ROUTE. Continue monitoring field conditions.';}catch{const note=document.querySelector<HTMLElement>('[data-live-route-note]');if(note)note.textContent='Could not start guidance. Recheck the incident and route.';}}
function ensureToolbar(){const toolbar=document.querySelector<HTMLElement>('.ops-map-toolbar');if(!toolbar||toolbar.querySelector('[data-route-layer-toggle]'))return;const routes=document.createElement('button');routes.type='button';routes.dataset.routeLayerToggle='true';routes.className='active';routes.textContent='Routes';routes.onclick=()=>{showRoutes=!showRoutes;routes.classList.toggle('active',showRoutes);document.querySelector<HTMLElement>('[data-live-route-layer]')?.classList.toggle('hidden',!showRoutes);};const risk=document.createElement('button');risk.type='button';risk.dataset.riskLayerToggle='true';risk.className='active';risk.textContent='Risk areas';risk.onclick=()=>{showRisk=!showRisk;risk.classList.toggle('active',showRisk);document.querySelectorAll<HTMLElement>('.ops-risk-wash').forEach(el=>el.style.display=showRisk?'':'none');};toolbar.prepend(risk);toolbar.prepend(routes);}
function render(){const page=document.querySelector<HTMLElement>('.ops-map-page');if(!page)return;ensureToolbar();const handoff=readHandoff();const map=document.querySelector<HTMLElement>('.ops-operations-map');const side=document.querySelector<HTMLElement>('.ops-map-side');if(!handoff||!map||!side){document.querySelector('[data-live-route-card]')?.remove();document.querySelector('[data-live-route-layer]')?.remove();return;}const img=map.querySelector<HTMLImageElement>('.ops-map-basemap');const bounds=img?parseBounds(img.src):null;if(!bounds)return;let layer=map.querySelector<HTMLElement>('[data-live-route-layer]');if(!layer){layer=document.createElement('div');layer.dataset.liveRouteLayer='true';layer.className='live-route-layer';map.appendChild(layer);}const responder=project(handoff.responderPosition.longitude,handoff.responderPosition.latitude,bounds);layer.innerHTML=`${routeSvg(handoff,bounds)}<div class="live-responder-marker" style="left:${responder.x}%;top:${responder.y}%"><span>R</span><b>RESPONDER</b></div>`;layer.classList.toggle('hidden',!showRoutes);
const recommended=handoff.candidates.find(r=>r.status==='recommended');const rejected=handoff.candidates.filter(r=>r.status==='rejected').length;const viable=handoff.candidates.filter(r=>r.status==='recommended'||r.status==='viable').length;let card=side.querySelector<HTMLElement>('[data-live-route-card]');if(!card){card=document.createElement('section');card.dataset.liveRouteCard='true';card.className='live-route-card';side.prepend(card);}card.innerHTML=`<div class="live-route-card-head"><div><span>LIVE RESPONSE ROUTE</span><h3>${recommended?'Recommended route active':'No recommended route'}</h3></div><b>${handoff.candidates.length} ANALYZED</b></div><div class="live-route-counts"><div><strong>${rejected}</strong><span>REJECTED</span></div><div><strong>${viable}</strong><span>VIABLE</span></div><div><strong>${recommended?1:0}</strong><span>RECOMMENDED</span></div></div>${recommended?`<div class="live-route-primary"><div><span>ETA</span><strong>${fmtDuration(recommended.durationS)}</strong></div><div><span>DISTANCE</span><strong>${fmtDistance(recommended.distanceM)}</strong></div><div><span>SAFETY</span><strong>${recommended.safetyScore}/100</strong></div></div><p class="live-route-why">${recommended.reason}</p><button type="button" data-live-start-guidance>START GUIDANCE</button>`:`<p class="live-route-warning">Every available route failed the current safety screen. Do not dispatch until conditions are rechecked.</p>`}<p data-live-route-note class="live-route-note">Route lines: gold = recommended, gray = viable, red dashed = rejected.</p>`;card.querySelector<HTMLButtonElement>('[data-live-start-guidance]')?.addEventListener('click',()=>void startGuidance(handoff));}
function schedule(){if(scheduled)return;scheduled=true;window.setTimeout(()=>{scheduled=false;render();},100);}const observer=new MutationObserver(schedule);const start=()=>{observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('jalrakshak:live-route-opened',schedule);schedule();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
